name: Run Python tester
on:
  pull_request:
    branches: [main]
  push:
    branches: 
      - main
      - devs
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
            
      - name: Install testing dependencies
        run: pip install -r ./requirements.txt coverage pytest

      - name: Check for test files
        id: check-tests
        run: |
            if find . -name "test_*.py" -o -name "*_test.py" | grep -q .; then
              echo "tests_exist=true" >> $GITHUB_OUTPUT
            else
              echo "tests_exist=false" >> $GITHUB_OUTPUT
            fi

      - name: Run testing
        if: steps.check-tests.outputs.tests_exist == 'true'
        run: |
            coverage run --source=. --omit="*/components/*,app.py" -m pytest
            coverage report

      - name: Skip testing
        if: steps.check-tests.outputs.tests_exist == 'false'
        run: echo "No test files found. Skipping tests."