name: Run Python tester
on:
  pull_request:
    branches: [main]
  push:
    branches: 
      - main
      - devs
jobs:
  development:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
            
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
            
      - name: Install testing dependencies
        run: pip install -r ./requirements.txt coverage

      - name: Run testing
        run: |
          coverage run --source ./app.py test
          coverage report